import React from 'react'
import type { RecommendedAction } from '../../types'
import { CheckCircle2, Clock, AlertCircle, Shield } from 'lucide-react'

interface RecommendedActionListProps {
  actions: RecommendedAction[]
  className?: string
}

export const RecommendedActionList: React.FC<RecommendedActionListProps> = ({
  actions,
  className = '',
}) => {
  if (!actions || actions.length === 0) {
    return (
      <div className="rounded-lg border border-slate-200 bg-white p-5 text-center text-xs text-slate-500">
        Standard administrative monitoring protocols apply. No special verification steps assigned.
      </div>
    )
  }

  const priorityStyles = {
    Immediate: 'text-rose-700 bg-rose-50 border-rose-200',
    High: 'text-amber-700 bg-amber-50 border-amber-200',
    Standard: 'text-slate-700 bg-slate-100 border-slate-200',
  }

  const statusIcons = {
    Completed: <CheckCircle2 size={14} className="text-emerald-600" />,
    'In Progress': <Clock size={14} className="text-blue-600" />,
    Pending: <AlertCircle size={14} className="text-slate-400" />,
  }

  return (
    <div className={`rounded-lg border border-slate-200/90 bg-white p-5 shadow-2xs ${className}`}>
      <div className="flex items-center justify-between border-b border-slate-100 pb-3">
        <div>
          <h4 className="text-xs font-bold uppercase tracking-wider text-slate-900 font-mono">
            Recommended Verification Actions
          </h4>
          <p className="text-xs text-slate-500 mt-0.5">
            Sequential protocol generated by decision intelligence to support official review.
          </p>
        </div>
        <span className="text-xs font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded">
          {actions.length} Recommended Steps
        </span>
      </div>

      <div className="mt-4 space-y-2.5">
        {actions.map((act) => (
          <div
            key={act.id}
            className="p-3 rounded-lg border border-slate-200/80 bg-slate-50/50 hover:bg-slate-50 flex items-start gap-3 transition-colors"
          >
            {/* Step Number Circle */}
            <div className="w-6 h-6 rounded-full bg-slate-200 text-slate-700 font-mono font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">
              {act.step}
            </div>

            {/* Action Details */}
            <div className="min-w-0 flex-1">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <span className="text-xs font-bold text-slate-900">{act.title}</span>
                <div className="flex items-center gap-1.5">
                  <span
                    className={`text-[10px] font-mono px-1.5 py-0.5 rounded border uppercase ${
                      priorityStyles[act.priority]
                    }`}
                  >
                    {act.priority}
                  </span>
                  <span className="flex items-center gap-1 text-[11px] font-mono text-slate-600 bg-white px-1.5 py-0.5 rounded border border-slate-200">
                    {statusIcons[act.status]}
                    {act.status}
                  </span>
                </div>
              </div>

              <p className="mt-1 text-xs text-slate-600 leading-snug">{act.reason}</p>

              <div className="mt-2 flex items-center gap-1.5 text-[11px] text-slate-500">
                <Shield size={12} className="text-slate-400" />
                <span>Assigned Authority: <strong className="text-slate-700 font-medium">{act.assignedAuthority}</strong></span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
